# Generated by Django 2.2.5 on 2021-03-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('nickname', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='dynasty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poem.Dynasty'),
        ),
        migrations.AddField(
            model_name='poem',
            name='theme',
            field=models.ManyToManyField(blank=True, to='poem.Theme'),
        ),
    ]
